// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="test_test,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.949000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=2963,HLS_VERSION=2020_2}" *)

module top_mul (
input   wire ap_clk,
input   wire ap_rst_n,
input   wire ap_start,
output  wire ap_done,
output  wire ap_idle,
output  wire ap_ready,
input   wire inStream1_TVALID,
input   wire inStream2_TVALID,
input   wire outStream_TREADY,
input  wire [511:0] inStream1_TDATA, //add tlast
output  wire  inStream1_TREADY,
input  wire [63:0] inStream1_TKEEP,
input  wire [63:0] inStream1_TSTRB,
input  wire [0:0] inStream1_TLAST,
input  wire [511:0] inStream2_TDATA,
output wire  inStream2_TREADY,
input  wire [63:0] inStream2_TKEEP,
input  wire [63:0] inStream2_TSTRB,
input  wire [0:0] inStream2_TLAST,
output  wire [511:0] outStream_TDATA,
output  wire  outStream_TVALID,
output  wire [63:0] outStream_TKEEP,
output  wire [63:0] outStream_TSTRB,
output  wire [0:0] outStream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;


reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_outStream_V_data_V_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    inStream1_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    inStream2_TDATA_blk_n;
reg    outStream_TDATA_blk_n;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
wire  signed [31:0] trunc_ln674_1_fu_179_p1;
wire  signed [31:0] trunc_ln674_fu_175_p1;
wire  signed [31:0] mul_ln691_1_fu_489_p0;
wire  signed [31:0] mul_ln691_1_fu_489_p1;
wire  signed [31:0] mul_ln691_2_fu_495_p0;
wire  signed [31:0] mul_ln691_2_fu_495_p1;
wire  signed [31:0] mul_ln691_3_fu_501_p0;
wire  signed [31:0] mul_ln691_3_fu_501_p1;
wire   [31:0] mul_ln691_1_fu_489_p2;
wire   [31:0] mul_ln691_fu_483_p2;
wire   [31:0] mul_ln691_2_fu_495_p2;
wire   [31:0] mul_ln691_3_fu_501_p2;
wire   [31:0] add_ln691_1_fu_513_p2;
wire   [31:0] add_ln691_fu_507_p2;
wire  signed [31:0] mul_ln691_4_fu_525_p0;
wire  signed [31:0] mul_ln691_5_fu_531_p0;
wire  signed [31:0] mul_ln691_5_fu_531_p1;
wire  signed [31:0] mul_ln691_6_fu_537_p0;
wire  signed [31:0] mul_ln691_6_fu_537_p1;
wire  signed [31:0] mul_ln691_7_fu_543_p0;
wire  signed [31:0] mul_ln691_7_fu_543_p1;
wire   [31:0] mul_ln691_5_fu_531_p2;
wire   [31:0] mul_ln691_4_fu_525_p2;
wire   [31:0] mul_ln691_6_fu_537_p2;
wire   [31:0] mul_ln691_7_fu_543_p2;
wire   [31:0] add_ln691_4_fu_555_p2;
wire   [31:0] add_ln691_3_fu_549_p2;
wire  signed [31:0] mul_ln691_8_fu_567_p0;
wire  signed [31:0] mul_ln691_9_fu_573_p0;
wire  signed [31:0] mul_ln691_9_fu_573_p1;
wire  signed [31:0] mul_ln691_10_fu_579_p0;
wire  signed [31:0] mul_ln691_10_fu_579_p1;
wire  signed [31:0] mul_ln691_11_fu_585_p0;
wire  signed [31:0] mul_ln691_11_fu_585_p1;
wire   [31:0] mul_ln691_9_fu_573_p2;
wire   [31:0] mul_ln691_8_fu_567_p2;
wire   [31:0] mul_ln691_10_fu_579_p2;
wire   [31:0] mul_ln691_11_fu_585_p2;
wire   [31:0] add_ln691_7_fu_597_p2;
wire   [31:0] add_ln691_6_fu_591_p2;
wire  signed [31:0] mul_ln691_12_fu_609_p0;
wire  signed [31:0] mul_ln691_13_fu_615_p0;
wire  signed [31:0] mul_ln691_13_fu_615_p1;
wire  signed [31:0] mul_ln691_14_fu_621_p0;
wire  signed [31:0] mul_ln691_14_fu_621_p1;
wire  signed [31:0] mul_ln691_15_fu_627_p0;
wire  signed [31:0] mul_ln691_15_fu_627_p1;
wire   [31:0] mul_ln691_13_fu_615_p2;
wire   [31:0] mul_ln691_12_fu_609_p2;
wire   [31:0] mul_ln691_14_fu_621_p2;
wire   [31:0] mul_ln691_15_fu_627_p2;
wire   [31:0] add_ln691_10_fu_639_p2;
wire   [31:0] add_ln691_9_fu_633_p2;
wire  signed [31:0] mul_ln691_16_fu_651_p1;
wire  signed [31:0] mul_ln691_17_fu_657_p0;
wire  signed [31:0] mul_ln691_17_fu_657_p1;
wire  signed [31:0] mul_ln691_18_fu_663_p0;
wire  signed [31:0] mul_ln691_18_fu_663_p1;
wire  signed [31:0] mul_ln691_19_fu_669_p0;
wire  signed [31:0] mul_ln691_19_fu_669_p1;
wire   [31:0] mul_ln691_17_fu_657_p2;
wire   [31:0] mul_ln691_16_fu_651_p2;
wire   [31:0] mul_ln691_18_fu_663_p2;
wire   [31:0] mul_ln691_19_fu_669_p2;
wire   [31:0] add_ln691_13_fu_681_p2;
wire   [31:0] add_ln691_12_fu_675_p2;
wire  signed [31:0] mul_ln691_20_fu_693_p0;
wire  signed [31:0] mul_ln691_20_fu_693_p1;
wire  signed [31:0] mul_ln691_21_fu_699_p0;
wire  signed [31:0] mul_ln691_21_fu_699_p1;
wire  signed [31:0] mul_ln691_22_fu_705_p0;
wire  signed [31:0] mul_ln691_22_fu_705_p1;
wire  signed [31:0] mul_ln691_23_fu_711_p0;
wire  signed [31:0] mul_ln691_23_fu_711_p1;
wire   [31:0] mul_ln691_21_fu_699_p2;
wire   [31:0] mul_ln691_20_fu_693_p2;
wire   [31:0] mul_ln691_22_fu_705_p2;
wire   [31:0] mul_ln691_23_fu_711_p2;
wire   [31:0] add_ln691_16_fu_723_p2;
wire   [31:0] add_ln691_15_fu_717_p2;
wire  signed [31:0] mul_ln691_24_fu_735_p0;
wire  signed [31:0] mul_ln691_24_fu_735_p1;
wire  signed [31:0] mul_ln691_25_fu_741_p0;
wire  signed [31:0] mul_ln691_25_fu_741_p1;
wire  signed [31:0] mul_ln691_26_fu_747_p0;
wire  signed [31:0] mul_ln691_26_fu_747_p1;
wire  signed [31:0] mul_ln691_27_fu_753_p0;
wire  signed [31:0] mul_ln691_27_fu_753_p1;
wire   [31:0] mul_ln691_25_fu_741_p2;
wire   [31:0] mul_ln691_24_fu_735_p2;
wire   [31:0] mul_ln691_26_fu_747_p2;
wire   [31:0] mul_ln691_27_fu_753_p2;
wire   [31:0] add_ln691_19_fu_765_p2;
wire   [31:0] add_ln691_18_fu_759_p2;
wire  signed [31:0] mul_ln691_28_fu_777_p0;
wire  signed [31:0] mul_ln691_28_fu_777_p1;
wire  signed [31:0] mul_ln691_29_fu_783_p0;
wire  signed [31:0] mul_ln691_29_fu_783_p1;
wire  signed [31:0] mul_ln691_30_fu_789_p0;
wire  signed [31:0] mul_ln691_30_fu_789_p1;
wire  signed [31:0] mul_ln691_31_fu_795_p0;
wire  signed [31:0] mul_ln691_31_fu_795_p1;
wire   [31:0] mul_ln691_29_fu_783_p2;
wire   [31:0] mul_ln691_28_fu_777_p2;
wire   [31:0] mul_ln691_30_fu_789_p2;
wire   [31:0] mul_ln691_31_fu_795_p2;
wire   [31:0] add_ln691_22_fu_807_p2;
wire   [31:0] add_ln691_21_fu_801_p2;
wire  signed [31:0] mul_ln691_32_fu_819_p1;
wire  signed [31:0] mul_ln691_33_fu_825_p0;
wire  signed [31:0] mul_ln691_33_fu_825_p1;
wire  signed [31:0] mul_ln691_34_fu_831_p0;
wire  signed [31:0] mul_ln691_34_fu_831_p1;
wire  signed [31:0] mul_ln691_35_fu_837_p0;
wire  signed [31:0] mul_ln691_35_fu_837_p1;
wire   [31:0] mul_ln691_33_fu_825_p2;
wire   [31:0] mul_ln691_32_fu_819_p2;
wire   [31:0] mul_ln691_34_fu_831_p2;
wire   [31:0] mul_ln691_35_fu_837_p2;
wire   [31:0] add_ln691_25_fu_849_p2;
wire   [31:0] add_ln691_24_fu_843_p2;
wire  signed [31:0] mul_ln691_36_fu_861_p0;
wire  signed [31:0] mul_ln691_36_fu_861_p1;
wire  signed [31:0] mul_ln691_37_fu_867_p0;
wire  signed [31:0] mul_ln691_37_fu_867_p1;
wire  signed [31:0] mul_ln691_38_fu_873_p0;
wire  signed [31:0] mul_ln691_38_fu_873_p1;
wire  signed [31:0] mul_ln691_39_fu_879_p0;
wire  signed [31:0] mul_ln691_39_fu_879_p1;
wire   [31:0] mul_ln691_37_fu_867_p2;
wire   [31:0] mul_ln691_36_fu_861_p2;
wire   [31:0] mul_ln691_38_fu_873_p2;
wire   [31:0] mul_ln691_39_fu_879_p2;
wire   [31:0] add_ln691_28_fu_891_p2;
wire   [31:0] add_ln691_27_fu_885_p2;
wire  signed [31:0] mul_ln691_40_fu_903_p0;
wire  signed [31:0] mul_ln691_40_fu_903_p1;
wire  signed [31:0] mul_ln691_41_fu_909_p0;
wire  signed [31:0] mul_ln691_41_fu_909_p1;
wire  signed [31:0] mul_ln691_42_fu_915_p0;
wire  signed [31:0] mul_ln691_42_fu_915_p1;
wire  signed [31:0] mul_ln691_43_fu_921_p0;
wire  signed [31:0] mul_ln691_43_fu_921_p1;
wire   [31:0] mul_ln691_41_fu_909_p2;
wire   [31:0] mul_ln691_40_fu_903_p2;
wire   [31:0] mul_ln691_42_fu_915_p2;
wire   [31:0] mul_ln691_43_fu_921_p2;
wire   [31:0] add_ln691_31_fu_933_p2;
wire   [31:0] add_ln691_30_fu_927_p2;
wire  signed [31:0] mul_ln691_44_fu_945_p0;
wire  signed [31:0] mul_ln691_44_fu_945_p1;
wire  signed [31:0] mul_ln691_45_fu_951_p0;
wire  signed [31:0] mul_ln691_45_fu_951_p1;
wire  signed [31:0] mul_ln691_46_fu_957_p0;
wire  signed [31:0] mul_ln691_46_fu_957_p1;
wire  signed [31:0] mul_ln691_47_fu_963_p0;
wire  signed [31:0] mul_ln691_47_fu_963_p1;
wire   [31:0] mul_ln691_45_fu_951_p2;
wire   [31:0] mul_ln691_44_fu_945_p2;
wire   [31:0] mul_ln691_46_fu_957_p2;
wire   [31:0] mul_ln691_47_fu_963_p2;
wire   [31:0] add_ln691_34_fu_975_p2;
wire   [31:0] add_ln691_33_fu_969_p2;
wire  signed [31:0] mul_ln691_48_fu_987_p1;
wire  signed [31:0] mul_ln691_49_fu_993_p0;
wire  signed [31:0] mul_ln691_49_fu_993_p1;
wire  signed [31:0] mul_ln691_50_fu_999_p0;
wire  signed [31:0] mul_ln691_50_fu_999_p1;
wire  signed [31:0] mul_ln691_51_fu_1005_p0;
wire  signed [31:0] mul_ln691_51_fu_1005_p1;
wire   [31:0] mul_ln691_49_fu_993_p2;
wire   [31:0] mul_ln691_48_fu_987_p2;
wire   [31:0] mul_ln691_50_fu_999_p2;
wire   [31:0] mul_ln691_51_fu_1005_p2;
wire   [31:0] add_ln691_37_fu_1017_p2;
wire   [31:0] add_ln691_36_fu_1011_p2;
wire  signed [31:0] mul_ln691_52_fu_1029_p0;
wire  signed [31:0] mul_ln691_52_fu_1029_p1;
wire  signed [31:0] mul_ln691_53_fu_1035_p0;
wire  signed [31:0] mul_ln691_53_fu_1035_p1;
wire  signed [31:0] mul_ln691_54_fu_1041_p0;
wire  signed [31:0] mul_ln691_54_fu_1041_p1;
wire  signed [31:0] mul_ln691_55_fu_1047_p0;
wire  signed [31:0] mul_ln691_55_fu_1047_p1;
wire   [31:0] mul_ln691_53_fu_1035_p2;
wire   [31:0] mul_ln691_52_fu_1029_p2;
wire   [31:0] mul_ln691_54_fu_1041_p2;
wire   [31:0] mul_ln691_55_fu_1047_p2;
wire   [31:0] add_ln691_40_fu_1059_p2;
wire   [31:0] add_ln691_39_fu_1053_p2;
wire  signed [31:0] mul_ln691_56_fu_1071_p0;
wire  signed [31:0] mul_ln691_56_fu_1071_p1;
wire  signed [31:0] mul_ln691_57_fu_1077_p0;
wire  signed [31:0] mul_ln691_57_fu_1077_p1;
wire  signed [31:0] mul_ln691_58_fu_1083_p0;
wire  signed [31:0] mul_ln691_58_fu_1083_p1;
wire  signed [31:0] mul_ln691_59_fu_1089_p0;
wire  signed [31:0] mul_ln691_59_fu_1089_p1;
wire   [31:0] mul_ln691_57_fu_1077_p2;
wire   [31:0] mul_ln691_56_fu_1071_p2;
wire   [31:0] mul_ln691_58_fu_1083_p2;
wire   [31:0] mul_ln691_59_fu_1089_p2;
wire   [31:0] add_ln691_43_fu_1101_p2;
wire   [31:0] add_ln691_42_fu_1095_p2;
wire  signed [31:0] mul_ln691_60_fu_1113_p0;
wire  signed [31:0] mul_ln691_60_fu_1113_p1;
wire  signed [31:0] mul_ln691_61_fu_1119_p0;
wire  signed [31:0] mul_ln691_61_fu_1119_p1;
wire  signed [31:0] mul_ln691_62_fu_1125_p0;
wire  signed [31:0] mul_ln691_62_fu_1125_p1;
wire  signed [31:0] mul_ln691_63_fu_1131_p0;
wire  signed [31:0] mul_ln691_63_fu_1131_p1;
wire   [31:0] mul_ln691_61_fu_1119_p2;
wire   [31:0] mul_ln691_60_fu_1113_p2;
wire   [31:0] mul_ln691_62_fu_1125_p2;
wire   [31:0] mul_ln691_63_fu_1131_p2;
wire   [31:0] add_ln691_46_fu_1143_p2;
wire   [31:0] add_ln691_45_fu_1137_p2;
wire   [31:0] add_ln691_47_fu_1149_p2;
wire   [31:0] add_ln691_44_fu_1107_p2;
wire   [31:0] add_ln691_41_fu_1065_p2;
wire   [31:0] add_ln691_38_fu_1023_p2;
wire   [31:0] add_ln691_35_fu_981_p2;
wire   [31:0] add_ln691_32_fu_939_p2;
wire   [31:0] add_ln691_29_fu_897_p2;
wire   [31:0] add_ln691_26_fu_855_p2;
wire   [31:0] add_ln691_23_fu_813_p2;
wire   [31:0] add_ln691_20_fu_771_p2;
wire   [31:0] add_ln691_17_fu_729_p2;
wire   [31:0] add_ln691_14_fu_687_p2;
wire   [31:0] add_ln691_11_fu_645_p2;
wire   [31:0] add_ln691_8_fu_603_p2;
wire   [31:0] add_ln691_5_fu_561_p2;
wire   [31:0] add_ln691_2_fu_519_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_inStream1_V_data_V_U_apdone_blk;
wire   [511:0] inStream1_TDATA_int_regslice;
wire    inStream1_TVALID_int_regslice;
reg    inStream1_TREADY_int_regslice;
wire    regslice_both_inStream1_V_data_V_U_ack_in;
wire    regslice_both_inStream1_V_keep_V_U_apdone_blk;
wire   [63:0] inStream1_TKEEP_int_regslice;
wire    regslice_both_inStream1_V_keep_V_U_vld_out;
wire    regslice_both_inStream1_V_keep_V_U_ack_in;
wire    regslice_both_inStream1_V_strb_V_U_apdone_blk;
wire   [63:0] inStream1_TSTRB_int_regslice;
wire    regslice_both_inStream1_V_strb_V_U_vld_out;
wire    regslice_both_inStream1_V_strb_V_U_ack_in;
wire    regslice_both_inStream1_V_last_V_U_apdone_blk;
wire   [0:0] inStream1_TLAST_int_regslice;
wire    regslice_both_inStream1_V_last_V_U_vld_out;
wire    regslice_both_inStream1_V_last_V_U_ack_in;
wire    regslice_both_inStream2_V_data_V_U_apdone_blk;
wire   [511:0] inStream2_TDATA_int_regslice;
wire    inStream2_TVALID_int_regslice;
reg    inStream2_TREADY_int_regslice;
wire    regslice_both_inStream2_V_data_V_U_ack_in;
wire    regslice_both_inStream2_V_keep_V_U_apdone_blk;
wire   [63:0] inStream2_TKEEP_int_regslice;
wire    regslice_both_inStream2_V_keep_V_U_vld_out;
wire    regslice_both_inStream2_V_keep_V_U_ack_in;
wire    regslice_both_inStream2_V_strb_V_U_apdone_blk;
wire   [63:0] inStream2_TSTRB_int_regslice;
wire    regslice_both_inStream2_V_strb_V_U_vld_out;
wire    regslice_both_inStream2_V_strb_V_U_ack_in;
wire    regslice_both_inStream2_V_last_V_U_apdone_blk;
wire   [0:0] inStream2_TLAST_int_regslice;
wire    regslice_both_inStream2_V_last_V_U_vld_out;
wire    regslice_both_inStream2_V_last_V_U_ack_in;
wire   [511:0] outStream_TDATA_int_regslice;
reg    outStream_TVALID_int_regslice;
wire    outStream_TREADY_int_regslice;
wire    regslice_both_outStream_V_data_V_U_vld_out;
wire    regslice_both_outStream_V_keep_V_U_apdone_blk;
wire    regslice_both_outStream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_keep_V_U_vld_out;
wire    regslice_both_outStream_V_strb_V_U_apdone_blk;
wire    regslice_both_outStream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_strb_V_U_vld_out;
wire    regslice_both_outStream_V_last_V_U_apdone_blk;
wire    regslice_both_outStream_V_last_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U1(
    .din0(trunc_ln674_1_fu_179_p1),
    .din1(trunc_ln674_fu_175_p1),
    .dout(mul_ln691_fu_483_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U2(
    .din0(mul_ln691_1_fu_489_p0),
    .din1(mul_ln691_1_fu_489_p1),
    .dout(mul_ln691_1_fu_489_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U3(
    .din0(mul_ln691_2_fu_495_p0),
    .din1(mul_ln691_2_fu_495_p1),
    .dout(mul_ln691_2_fu_495_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U4(
    .din0(mul_ln691_3_fu_501_p0),
    .din1(mul_ln691_3_fu_501_p1),
    .dout(mul_ln691_3_fu_501_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U5(
    .din0(mul_ln691_4_fu_525_p0),
    .din1(trunc_ln674_fu_175_p1),
    .dout(mul_ln691_4_fu_525_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U6(
    .din0(mul_ln691_5_fu_531_p0),
    .din1(mul_ln691_5_fu_531_p1),
    .dout(mul_ln691_5_fu_531_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U7(
    .din0(mul_ln691_6_fu_537_p0),
    .din1(mul_ln691_6_fu_537_p1),
    .dout(mul_ln691_6_fu_537_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U8(
    .din0(mul_ln691_7_fu_543_p0),
    .din1(mul_ln691_7_fu_543_p1),
    .dout(mul_ln691_7_fu_543_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U9(
    .din0(mul_ln691_8_fu_567_p0),
    .din1(trunc_ln674_fu_175_p1),
    .dout(mul_ln691_8_fu_567_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U10(
    .din0(mul_ln691_9_fu_573_p0),
    .din1(mul_ln691_9_fu_573_p1),
    .dout(mul_ln691_9_fu_573_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U11(
    .din0(mul_ln691_10_fu_579_p0),
    .din1(mul_ln691_10_fu_579_p1),
    .dout(mul_ln691_10_fu_579_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U12(
    .din0(mul_ln691_11_fu_585_p0),
    .din1(mul_ln691_11_fu_585_p1),
    .dout(mul_ln691_11_fu_585_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U13(
    .din0(mul_ln691_12_fu_609_p0),
    .din1(trunc_ln674_fu_175_p1),
    .dout(mul_ln691_12_fu_609_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U14(
    .din0(mul_ln691_13_fu_615_p0),
    .din1(mul_ln691_13_fu_615_p1),
    .dout(mul_ln691_13_fu_615_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U15(
    .din0(mul_ln691_14_fu_621_p0),
    .din1(mul_ln691_14_fu_621_p1),
    .dout(mul_ln691_14_fu_621_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U16(
    .din0(mul_ln691_15_fu_627_p0),
    .din1(mul_ln691_15_fu_627_p1),
    .dout(mul_ln691_15_fu_627_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U17(
    .din0(trunc_ln674_1_fu_179_p1),
    .din1(mul_ln691_16_fu_651_p1),
    .dout(mul_ln691_16_fu_651_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U18(
    .din0(mul_ln691_17_fu_657_p0),
    .din1(mul_ln691_17_fu_657_p1),
    .dout(mul_ln691_17_fu_657_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U19(
    .din0(mul_ln691_18_fu_663_p0),
    .din1(mul_ln691_18_fu_663_p1),
    .dout(mul_ln691_18_fu_663_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U20(
    .din0(mul_ln691_19_fu_669_p0),
    .din1(mul_ln691_19_fu_669_p1),
    .dout(mul_ln691_19_fu_669_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U21(
    .din0(mul_ln691_20_fu_693_p0),
    .din1(mul_ln691_20_fu_693_p1),
    .dout(mul_ln691_20_fu_693_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U22(
    .din0(mul_ln691_21_fu_699_p0),
    .din1(mul_ln691_21_fu_699_p1),
    .dout(mul_ln691_21_fu_699_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U23(
    .din0(mul_ln691_22_fu_705_p0),
    .din1(mul_ln691_22_fu_705_p1),
    .dout(mul_ln691_22_fu_705_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U24(
    .din0(mul_ln691_23_fu_711_p0),
    .din1(mul_ln691_23_fu_711_p1),
    .dout(mul_ln691_23_fu_711_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U25(
    .din0(mul_ln691_24_fu_735_p0),
    .din1(mul_ln691_24_fu_735_p1),
    .dout(mul_ln691_24_fu_735_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U26(
    .din0(mul_ln691_25_fu_741_p0),
    .din1(mul_ln691_25_fu_741_p1),
    .dout(mul_ln691_25_fu_741_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U27(
    .din0(mul_ln691_26_fu_747_p0),
    .din1(mul_ln691_26_fu_747_p1),
    .dout(mul_ln691_26_fu_747_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U28(
    .din0(mul_ln691_27_fu_753_p0),
    .din1(mul_ln691_27_fu_753_p1),
    .dout(mul_ln691_27_fu_753_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U29(
    .din0(mul_ln691_28_fu_777_p0),
    .din1(mul_ln691_28_fu_777_p1),
    .dout(mul_ln691_28_fu_777_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U30(
    .din0(mul_ln691_29_fu_783_p0),
    .din1(mul_ln691_29_fu_783_p1),
    .dout(mul_ln691_29_fu_783_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U31(
    .din0(mul_ln691_30_fu_789_p0),
    .din1(mul_ln691_30_fu_789_p1),
    .dout(mul_ln691_30_fu_789_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U32(
    .din0(mul_ln691_31_fu_795_p0),
    .din1(mul_ln691_31_fu_795_p1),
    .dout(mul_ln691_31_fu_795_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U33(
    .din0(trunc_ln674_1_fu_179_p1),
    .din1(mul_ln691_32_fu_819_p1),
    .dout(mul_ln691_32_fu_819_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U34(
    .din0(mul_ln691_33_fu_825_p0),
    .din1(mul_ln691_33_fu_825_p1),
    .dout(mul_ln691_33_fu_825_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U35(
    .din0(mul_ln691_34_fu_831_p0),
    .din1(mul_ln691_34_fu_831_p1),
    .dout(mul_ln691_34_fu_831_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U36(
    .din0(mul_ln691_35_fu_837_p0),
    .din1(mul_ln691_35_fu_837_p1),
    .dout(mul_ln691_35_fu_837_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U37(
    .din0(mul_ln691_36_fu_861_p0),
    .din1(mul_ln691_36_fu_861_p1),
    .dout(mul_ln691_36_fu_861_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U38(
    .din0(mul_ln691_37_fu_867_p0),
    .din1(mul_ln691_37_fu_867_p1),
    .dout(mul_ln691_37_fu_867_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U39(
    .din0(mul_ln691_38_fu_873_p0),
    .din1(mul_ln691_38_fu_873_p1),
    .dout(mul_ln691_38_fu_873_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U40(
    .din0(mul_ln691_39_fu_879_p0),
    .din1(mul_ln691_39_fu_879_p1),
    .dout(mul_ln691_39_fu_879_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U41(
    .din0(mul_ln691_40_fu_903_p0),
    .din1(mul_ln691_40_fu_903_p1),
    .dout(mul_ln691_40_fu_903_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U42(
    .din0(mul_ln691_41_fu_909_p0),
    .din1(mul_ln691_41_fu_909_p1),
    .dout(mul_ln691_41_fu_909_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U43(
    .din0(mul_ln691_42_fu_915_p0),
    .din1(mul_ln691_42_fu_915_p1),
    .dout(mul_ln691_42_fu_915_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U44(
    .din0(mul_ln691_43_fu_921_p0),
    .din1(mul_ln691_43_fu_921_p1),
    .dout(mul_ln691_43_fu_921_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U45(
    .din0(mul_ln691_44_fu_945_p0),
    .din1(mul_ln691_44_fu_945_p1),
    .dout(mul_ln691_44_fu_945_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U46(
    .din0(mul_ln691_45_fu_951_p0),
    .din1(mul_ln691_45_fu_951_p1),
    .dout(mul_ln691_45_fu_951_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U47(
    .din0(mul_ln691_46_fu_957_p0),
    .din1(mul_ln691_46_fu_957_p1),
    .dout(mul_ln691_46_fu_957_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U48(
    .din0(mul_ln691_47_fu_963_p0),
    .din1(mul_ln691_47_fu_963_p1),
    .dout(mul_ln691_47_fu_963_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U49(
    .din0(trunc_ln674_1_fu_179_p1),
    .din1(mul_ln691_48_fu_987_p1),
    .dout(mul_ln691_48_fu_987_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U50(
    .din0(mul_ln691_49_fu_993_p0),
    .din1(mul_ln691_49_fu_993_p1),
    .dout(mul_ln691_49_fu_993_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U51(
    .din0(mul_ln691_50_fu_999_p0),
    .din1(mul_ln691_50_fu_999_p1),
    .dout(mul_ln691_50_fu_999_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U52(
    .din0(mul_ln691_51_fu_1005_p0),
    .din1(mul_ln691_51_fu_1005_p1),
    .dout(mul_ln691_51_fu_1005_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U53(
    .din0(mul_ln691_52_fu_1029_p0),
    .din1(mul_ln691_52_fu_1029_p1),
    .dout(mul_ln691_52_fu_1029_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U54(
    .din0(mul_ln691_53_fu_1035_p0),
    .din1(mul_ln691_53_fu_1035_p1),
    .dout(mul_ln691_53_fu_1035_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U55(
    .din0(mul_ln691_54_fu_1041_p0),
    .din1(mul_ln691_54_fu_1041_p1),
    .dout(mul_ln691_54_fu_1041_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U56(
    .din0(mul_ln691_55_fu_1047_p0),
    .din1(mul_ln691_55_fu_1047_p1),
    .dout(mul_ln691_55_fu_1047_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U57(
    .din0(mul_ln691_56_fu_1071_p0),
    .din1(mul_ln691_56_fu_1071_p1),
    .dout(mul_ln691_56_fu_1071_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U58(
    .din0(mul_ln691_57_fu_1077_p0),
    .din1(mul_ln691_57_fu_1077_p1),
    .dout(mul_ln691_57_fu_1077_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U59(
    .din0(mul_ln691_58_fu_1083_p0),
    .din1(mul_ln691_58_fu_1083_p1),
    .dout(mul_ln691_58_fu_1083_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U60(
    .din0(mul_ln691_59_fu_1089_p0),
    .din1(mul_ln691_59_fu_1089_p1),
    .dout(mul_ln691_59_fu_1089_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U61(
    .din0(mul_ln691_60_fu_1113_p0),
    .din1(mul_ln691_60_fu_1113_p1),
    .dout(mul_ln691_60_fu_1113_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U62(
    .din0(mul_ln691_61_fu_1119_p0),
    .din1(mul_ln691_61_fu_1119_p1),
    .dout(mul_ln691_61_fu_1119_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U63(
    .din0(mul_ln691_62_fu_1125_p0),
    .din1(mul_ln691_62_fu_1125_p1),
    .dout(mul_ln691_62_fu_1125_p2)
);

test_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U64(
    .din0(mul_ln691_63_fu_1131_p0),
    .din1(mul_ln691_63_fu_1131_p1),
    .dout(mul_ln691_63_fu_1131_p2)
);

test_regslice_both #(
    .DataWidth( 512 ))
regslice_both_inStream1_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream1_TDATA),
    .vld_in(inStream1_TVALID),
    .ack_in(regslice_both_inStream1_V_data_V_U_ack_in),
    .data_out(inStream1_TDATA_int_regslice),
    .vld_out(inStream1_TVALID_int_regslice),
    .ack_out(inStream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream1_V_data_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 64 ))
regslice_both_inStream1_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream1_TKEEP),
    .vld_in(inStream1_TVALID),
    .ack_in(regslice_both_inStream1_V_keep_V_U_ack_in),
    .data_out(inStream1_TKEEP_int_regslice),
    .vld_out(regslice_both_inStream1_V_keep_V_U_vld_out),
    .ack_out(inStream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream1_V_keep_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 64 ))
regslice_both_inStream1_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream1_TSTRB),
    .vld_in(inStream1_TVALID),
    .ack_in(regslice_both_inStream1_V_strb_V_U_ack_in),
    .data_out(inStream1_TSTRB_int_regslice),
    .vld_out(regslice_both_inStream1_V_strb_V_U_vld_out),
    .ack_out(inStream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream1_V_strb_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream1_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream1_TLAST),
    .vld_in(inStream1_TVALID),
    .ack_in(regslice_both_inStream1_V_last_V_U_ack_in),
    .data_out(inStream1_TLAST_int_regslice),
    .vld_out(regslice_both_inStream1_V_last_V_U_vld_out),
    .ack_out(inStream1_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream1_V_last_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 512 ))
regslice_both_inStream2_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream2_TDATA),
    .vld_in(inStream2_TVALID),
    .ack_in(regslice_both_inStream2_V_data_V_U_ack_in),
    .data_out(inStream2_TDATA_int_regslice),
    .vld_out(inStream2_TVALID_int_regslice),
    .ack_out(inStream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream2_V_data_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 64 ))
regslice_both_inStream2_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream2_TKEEP),
    .vld_in(inStream2_TVALID),
    .ack_in(regslice_both_inStream2_V_keep_V_U_ack_in),
    .data_out(inStream2_TKEEP_int_regslice),
    .vld_out(regslice_both_inStream2_V_keep_V_U_vld_out),
    .ack_out(inStream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream2_V_keep_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 64 ))
regslice_both_inStream2_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream2_TSTRB),
    .vld_in(inStream2_TVALID),
    .ack_in(regslice_both_inStream2_V_strb_V_U_ack_in),
    .data_out(inStream2_TSTRB_int_regslice),
    .vld_out(regslice_both_inStream2_V_strb_V_U_vld_out),
    .ack_out(inStream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream2_V_strb_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream2_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream2_TLAST),
    .vld_in(inStream2_TVALID),
    .ack_in(regslice_both_inStream2_V_last_V_U_ack_in),
    .data_out(inStream2_TLAST_int_regslice),
    .vld_out(regslice_both_inStream2_V_last_V_U_vld_out),
    .ack_out(inStream2_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream2_V_last_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 512 ))
regslice_both_outStream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outStream_TDATA_int_regslice),
    .vld_in(outStream_TVALID_int_regslice),
    .ack_in(outStream_TREADY_int_regslice),
    .data_out(outStream_TDATA),
    .vld_out(regslice_both_outStream_V_data_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_data_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 64 ))
regslice_both_outStream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream1_TKEEP_int_regslice),
    .vld_in(outStream_TVALID_int_regslice),
    .ack_in(regslice_both_outStream_V_keep_V_U_ack_in_dummy),
    .data_out(outStream_TKEEP),
    .vld_out(regslice_both_outStream_V_keep_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_keep_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 64 ))
regslice_both_outStream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream1_TSTRB_int_regslice),
    .vld_in(outStream_TVALID_int_regslice),
    .ack_in(regslice_both_outStream_V_strb_V_U_ack_in_dummy),
    .data_out(outStream_TSTRB),
    .vld_out(regslice_both_outStream_V_strb_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_strb_V_U_apdone_blk)
);

test_regslice_both #(
    .DataWidth( 1 ))
regslice_both_outStream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(outStream_TVALID_int_regslice),
    .ack_in(regslice_both_outStream_V_last_V_U_ack_in_dummy),
    .data_out(outStream_TLAST),
    .vld_out(regslice_both_outStream_V_last_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inStream1_TDATA_blk_n = inStream1_TVALID_int_regslice;
    end else begin
        inStream1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inStream1_TREADY_int_regslice = 1'b1;
    end else begin
        inStream1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inStream2_TDATA_blk_n = inStream2_TVALID_int_regslice;
    end else begin
        inStream2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inStream2_TREADY_int_regslice = 1'b1;
    end else begin
        inStream2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        outStream_TDATA_blk_n = outStream_TREADY_int_regslice;
    end else begin
        outStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outStream_TVALID_int_regslice = 1'b1;
    end else begin
        outStream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln691_10_fu_639_p2 = (mul_ln691_14_fu_621_p2 + mul_ln691_15_fu_627_p2);

assign add_ln691_11_fu_645_p2 = (add_ln691_10_fu_639_p2 + add_ln691_9_fu_633_p2);

assign add_ln691_12_fu_675_p2 = (mul_ln691_17_fu_657_p2 + mul_ln691_16_fu_651_p2);

assign add_ln691_13_fu_681_p2 = (mul_ln691_18_fu_663_p2 + mul_ln691_19_fu_669_p2);

assign add_ln691_14_fu_687_p2 = (add_ln691_13_fu_681_p2 + add_ln691_12_fu_675_p2);

assign add_ln691_15_fu_717_p2 = (mul_ln691_21_fu_699_p2 + mul_ln691_20_fu_693_p2);

assign add_ln691_16_fu_723_p2 = (mul_ln691_22_fu_705_p2 + mul_ln691_23_fu_711_p2);

assign add_ln691_17_fu_729_p2 = (add_ln691_16_fu_723_p2 + add_ln691_15_fu_717_p2);

assign add_ln691_18_fu_759_p2 = (mul_ln691_25_fu_741_p2 + mul_ln691_24_fu_735_p2);

assign add_ln691_19_fu_765_p2 = (mul_ln691_26_fu_747_p2 + mul_ln691_27_fu_753_p2);

assign add_ln691_1_fu_513_p2 = (mul_ln691_2_fu_495_p2 + mul_ln691_3_fu_501_p2);

assign add_ln691_20_fu_771_p2 = (add_ln691_19_fu_765_p2 + add_ln691_18_fu_759_p2);

assign add_ln691_21_fu_801_p2 = (mul_ln691_29_fu_783_p2 + mul_ln691_28_fu_777_p2);

assign add_ln691_22_fu_807_p2 = (mul_ln691_30_fu_789_p2 + mul_ln691_31_fu_795_p2);

assign add_ln691_23_fu_813_p2 = (add_ln691_22_fu_807_p2 + add_ln691_21_fu_801_p2);

assign add_ln691_24_fu_843_p2 = (mul_ln691_33_fu_825_p2 + mul_ln691_32_fu_819_p2);

assign add_ln691_25_fu_849_p2 = (mul_ln691_34_fu_831_p2 + mul_ln691_35_fu_837_p2);

assign add_ln691_26_fu_855_p2 = (add_ln691_25_fu_849_p2 + add_ln691_24_fu_843_p2);

assign add_ln691_27_fu_885_p2 = (mul_ln691_37_fu_867_p2 + mul_ln691_36_fu_861_p2);

assign add_ln691_28_fu_891_p2 = (mul_ln691_38_fu_873_p2 + mul_ln691_39_fu_879_p2);

assign add_ln691_29_fu_897_p2 = (add_ln691_28_fu_891_p2 + add_ln691_27_fu_885_p2);

assign add_ln691_2_fu_519_p2 = (add_ln691_1_fu_513_p2 + add_ln691_fu_507_p2);

assign add_ln691_30_fu_927_p2 = (mul_ln691_41_fu_909_p2 + mul_ln691_40_fu_903_p2);

assign add_ln691_31_fu_933_p2 = (mul_ln691_42_fu_915_p2 + mul_ln691_43_fu_921_p2);

assign add_ln691_32_fu_939_p2 = (add_ln691_31_fu_933_p2 + add_ln691_30_fu_927_p2);

assign add_ln691_33_fu_969_p2 = (mul_ln691_45_fu_951_p2 + mul_ln691_44_fu_945_p2);

assign add_ln691_34_fu_975_p2 = (mul_ln691_46_fu_957_p2 + mul_ln691_47_fu_963_p2);

assign add_ln691_35_fu_981_p2 = (add_ln691_34_fu_975_p2 + add_ln691_33_fu_969_p2);

assign add_ln691_36_fu_1011_p2 = (mul_ln691_49_fu_993_p2 + mul_ln691_48_fu_987_p2);

assign add_ln691_37_fu_1017_p2 = (mul_ln691_50_fu_999_p2 + mul_ln691_51_fu_1005_p2);

assign add_ln691_38_fu_1023_p2 = (add_ln691_37_fu_1017_p2 + add_ln691_36_fu_1011_p2);

assign add_ln691_39_fu_1053_p2 = (mul_ln691_53_fu_1035_p2 + mul_ln691_52_fu_1029_p2);

assign add_ln691_3_fu_549_p2 = (mul_ln691_5_fu_531_p2 + mul_ln691_4_fu_525_p2);

assign add_ln691_40_fu_1059_p2 = (mul_ln691_54_fu_1041_p2 + mul_ln691_55_fu_1047_p2);

assign add_ln691_41_fu_1065_p2 = (add_ln691_40_fu_1059_p2 + add_ln691_39_fu_1053_p2);

assign add_ln691_42_fu_1095_p2 = (mul_ln691_57_fu_1077_p2 + mul_ln691_56_fu_1071_p2);

assign add_ln691_43_fu_1101_p2 = (mul_ln691_58_fu_1083_p2 + mul_ln691_59_fu_1089_p2);

assign add_ln691_44_fu_1107_p2 = (add_ln691_43_fu_1101_p2 + add_ln691_42_fu_1095_p2);

assign add_ln691_45_fu_1137_p2 = (mul_ln691_61_fu_1119_p2 + mul_ln691_60_fu_1113_p2);

assign add_ln691_46_fu_1143_p2 = (mul_ln691_62_fu_1125_p2 + mul_ln691_63_fu_1131_p2);

assign add_ln691_47_fu_1149_p2 = (add_ln691_46_fu_1143_p2 + add_ln691_45_fu_1137_p2);

assign add_ln691_4_fu_555_p2 = (mul_ln691_6_fu_537_p2 + mul_ln691_7_fu_543_p2);

assign add_ln691_5_fu_561_p2 = (add_ln691_4_fu_555_p2 + add_ln691_3_fu_549_p2);

assign add_ln691_6_fu_591_p2 = (mul_ln691_9_fu_573_p2 + mul_ln691_8_fu_567_p2);

assign add_ln691_7_fu_597_p2 = (mul_ln691_10_fu_579_p2 + mul_ln691_11_fu_585_p2);

assign add_ln691_8_fu_603_p2 = (add_ln691_7_fu_597_p2 + add_ln691_6_fu_591_p2);

assign add_ln691_9_fu_633_p2 = (mul_ln691_13_fu_615_p2 + mul_ln691_12_fu_609_p2);

assign add_ln691_fu_507_p2 = (mul_ln691_1_fu_489_p2 + mul_ln691_fu_483_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((outStream_TREADY_int_regslice == 1'b0) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1))) | ((ap_start == 1'b1) & ((outStream_TREADY_int_regslice == 1'b0) | (inStream2_TVALID_int_regslice == 1'b0) | (inStream1_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((outStream_TREADY_int_regslice == 1'b0) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1))) | ((ap_start == 1'b1) & ((outStream_TREADY_int_regslice == 1'b0) | (inStream2_TVALID_int_regslice == 1'b0) | (inStream1_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((outStream_TREADY_int_regslice == 1'b0) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1))) | ((ap_start == 1'b1) & ((outStream_TREADY_int_regslice == 1'b0) | (inStream2_TVALID_int_regslice == 1'b0) | (inStream1_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((outStream_TREADY_int_regslice == 1'b0) | (inStream2_TVALID_int_regslice == 1'b0) | (inStream1_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((outStream_TREADY_int_regslice == 1'b0) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign inStream1_TREADY = regslice_both_inStream1_V_data_V_U_ack_in;

assign inStream2_TREADY = regslice_both_inStream2_V_data_V_U_ack_in;

assign mul_ln691_10_fu_579_p0 = {{inStream2_TDATA_int_regslice[351:320]}};

assign mul_ln691_10_fu_579_p1 = {{inStream1_TDATA_int_regslice[95:64]}};

assign mul_ln691_11_fu_585_p0 = {{inStream2_TDATA_int_regslice[479:448]}};

assign mul_ln691_11_fu_585_p1 = {{inStream1_TDATA_int_regslice[127:96]}};

assign mul_ln691_12_fu_609_p0 = {{inStream2_TDATA_int_regslice[127:96]}};

assign mul_ln691_13_fu_615_p0 = {{inStream2_TDATA_int_regslice[255:224]}};

assign mul_ln691_13_fu_615_p1 = {{inStream1_TDATA_int_regslice[63:32]}};

assign mul_ln691_14_fu_621_p0 = {{inStream2_TDATA_int_regslice[383:352]}};

assign mul_ln691_14_fu_621_p1 = {{inStream1_TDATA_int_regslice[95:64]}};

assign mul_ln691_15_fu_627_p0 = {{inStream2_TDATA_int_regslice[511:480]}};

assign mul_ln691_15_fu_627_p1 = {{inStream1_TDATA_int_regslice[127:96]}};

assign mul_ln691_16_fu_651_p1 = {{inStream1_TDATA_int_regslice[159:128]}};

assign mul_ln691_17_fu_657_p0 = {{inStream2_TDATA_int_regslice[159:128]}};

assign mul_ln691_17_fu_657_p1 = {{inStream1_TDATA_int_regslice[191:160]}};

assign mul_ln691_18_fu_663_p0 = {{inStream2_TDATA_int_regslice[287:256]}};

assign mul_ln691_18_fu_663_p1 = {{inStream1_TDATA_int_regslice[223:192]}};

assign mul_ln691_19_fu_669_p0 = {{inStream2_TDATA_int_regslice[415:384]}};

assign mul_ln691_19_fu_669_p1 = {{inStream1_TDATA_int_regslice[255:224]}};

assign mul_ln691_1_fu_489_p0 = {{inStream2_TDATA_int_regslice[159:128]}};

assign mul_ln691_1_fu_489_p1 = {{inStream1_TDATA_int_regslice[63:32]}};

assign mul_ln691_20_fu_693_p0 = {{inStream2_TDATA_int_regslice[63:32]}};

assign mul_ln691_20_fu_693_p1 = {{inStream1_TDATA_int_regslice[159:128]}};

assign mul_ln691_21_fu_699_p0 = {{inStream2_TDATA_int_regslice[191:160]}};

assign mul_ln691_21_fu_699_p1 = {{inStream1_TDATA_int_regslice[191:160]}};

assign mul_ln691_22_fu_705_p0 = {{inStream2_TDATA_int_regslice[319:288]}};

assign mul_ln691_22_fu_705_p1 = {{inStream1_TDATA_int_regslice[223:192]}};

assign mul_ln691_23_fu_711_p0 = {{inStream2_TDATA_int_regslice[447:416]}};

assign mul_ln691_23_fu_711_p1 = {{inStream1_TDATA_int_regslice[255:224]}};

assign mul_ln691_24_fu_735_p0 = {{inStream2_TDATA_int_regslice[95:64]}};

assign mul_ln691_24_fu_735_p1 = {{inStream1_TDATA_int_regslice[159:128]}};

assign mul_ln691_25_fu_741_p0 = {{inStream2_TDATA_int_regslice[223:192]}};

assign mul_ln691_25_fu_741_p1 = {{inStream1_TDATA_int_regslice[191:160]}};

assign mul_ln691_26_fu_747_p0 = {{inStream2_TDATA_int_regslice[351:320]}};

assign mul_ln691_26_fu_747_p1 = {{inStream1_TDATA_int_regslice[223:192]}};

assign mul_ln691_27_fu_753_p0 = {{inStream2_TDATA_int_regslice[479:448]}};

assign mul_ln691_27_fu_753_p1 = {{inStream1_TDATA_int_regslice[255:224]}};

assign mul_ln691_28_fu_777_p0 = {{inStream2_TDATA_int_regslice[127:96]}};

assign mul_ln691_28_fu_777_p1 = {{inStream1_TDATA_int_regslice[159:128]}};

assign mul_ln691_29_fu_783_p0 = {{inStream2_TDATA_int_regslice[255:224]}};

assign mul_ln691_29_fu_783_p1 = {{inStream1_TDATA_int_regslice[191:160]}};

assign mul_ln691_2_fu_495_p0 = {{inStream2_TDATA_int_regslice[287:256]}};

assign mul_ln691_2_fu_495_p1 = {{inStream1_TDATA_int_regslice[95:64]}};

assign mul_ln691_30_fu_789_p0 = {{inStream2_TDATA_int_regslice[383:352]}};

assign mul_ln691_30_fu_789_p1 = {{inStream1_TDATA_int_regslice[223:192]}};

assign mul_ln691_31_fu_795_p0 = {{inStream2_TDATA_int_regslice[511:480]}};

assign mul_ln691_31_fu_795_p1 = {{inStream1_TDATA_int_regslice[255:224]}};

assign mul_ln691_32_fu_819_p1 = {{inStream1_TDATA_int_regslice[287:256]}};

assign mul_ln691_33_fu_825_p0 = {{inStream2_TDATA_int_regslice[159:128]}};

assign mul_ln691_33_fu_825_p1 = {{inStream1_TDATA_int_regslice[319:288]}};

assign mul_ln691_34_fu_831_p0 = {{inStream2_TDATA_int_regslice[287:256]}};

assign mul_ln691_34_fu_831_p1 = {{inStream1_TDATA_int_regslice[351:320]}};

assign mul_ln691_35_fu_837_p0 = {{inStream2_TDATA_int_regslice[415:384]}};

assign mul_ln691_35_fu_837_p1 = {{inStream1_TDATA_int_regslice[383:352]}};

assign mul_ln691_36_fu_861_p0 = {{inStream2_TDATA_int_regslice[63:32]}};

assign mul_ln691_36_fu_861_p1 = {{inStream1_TDATA_int_regslice[287:256]}};

assign mul_ln691_37_fu_867_p0 = {{inStream2_TDATA_int_regslice[191:160]}};

assign mul_ln691_37_fu_867_p1 = {{inStream1_TDATA_int_regslice[319:288]}};

assign mul_ln691_38_fu_873_p0 = {{inStream2_TDATA_int_regslice[319:288]}};

assign mul_ln691_38_fu_873_p1 = {{inStream1_TDATA_int_regslice[351:320]}};

assign mul_ln691_39_fu_879_p0 = {{inStream2_TDATA_int_regslice[447:416]}};

assign mul_ln691_39_fu_879_p1 = {{inStream1_TDATA_int_regslice[383:352]}};

assign mul_ln691_3_fu_501_p0 = {{inStream2_TDATA_int_regslice[415:384]}};

assign mul_ln691_3_fu_501_p1 = {{inStream1_TDATA_int_regslice[127:96]}};

assign mul_ln691_40_fu_903_p0 = {{inStream2_TDATA_int_regslice[95:64]}};

assign mul_ln691_40_fu_903_p1 = {{inStream1_TDATA_int_regslice[287:256]}};

assign mul_ln691_41_fu_909_p0 = {{inStream2_TDATA_int_regslice[223:192]}};

assign mul_ln691_41_fu_909_p1 = {{inStream1_TDATA_int_regslice[319:288]}};

assign mul_ln691_42_fu_915_p0 = {{inStream2_TDATA_int_regslice[351:320]}};

assign mul_ln691_42_fu_915_p1 = {{inStream1_TDATA_int_regslice[351:320]}};

assign mul_ln691_43_fu_921_p0 = {{inStream2_TDATA_int_regslice[479:448]}};

assign mul_ln691_43_fu_921_p1 = {{inStream1_TDATA_int_regslice[383:352]}};

assign mul_ln691_44_fu_945_p0 = {{inStream2_TDATA_int_regslice[127:96]}};

assign mul_ln691_44_fu_945_p1 = {{inStream1_TDATA_int_regslice[287:256]}};

assign mul_ln691_45_fu_951_p0 = {{inStream2_TDATA_int_regslice[255:224]}};

assign mul_ln691_45_fu_951_p1 = {{inStream1_TDATA_int_regslice[319:288]}};

assign mul_ln691_46_fu_957_p0 = {{inStream2_TDATA_int_regslice[383:352]}};

assign mul_ln691_46_fu_957_p1 = {{inStream1_TDATA_int_regslice[351:320]}};

assign mul_ln691_47_fu_963_p0 = {{inStream2_TDATA_int_regslice[511:480]}};

assign mul_ln691_47_fu_963_p1 = {{inStream1_TDATA_int_regslice[383:352]}};

assign mul_ln691_48_fu_987_p1 = {{inStream1_TDATA_int_regslice[415:384]}};

assign mul_ln691_49_fu_993_p0 = {{inStream2_TDATA_int_regslice[159:128]}};

assign mul_ln691_49_fu_993_p1 = {{inStream1_TDATA_int_regslice[447:416]}};

assign mul_ln691_4_fu_525_p0 = {{inStream2_TDATA_int_regslice[63:32]}};

assign mul_ln691_50_fu_999_p0 = {{inStream2_TDATA_int_regslice[287:256]}};

assign mul_ln691_50_fu_999_p1 = {{inStream1_TDATA_int_regslice[479:448]}};

assign mul_ln691_51_fu_1005_p0 = {{inStream2_TDATA_int_regslice[415:384]}};

assign mul_ln691_51_fu_1005_p1 = {{inStream1_TDATA_int_regslice[511:480]}};

assign mul_ln691_52_fu_1029_p0 = {{inStream2_TDATA_int_regslice[63:32]}};

assign mul_ln691_52_fu_1029_p1 = {{inStream1_TDATA_int_regslice[415:384]}};

assign mul_ln691_53_fu_1035_p0 = {{inStream2_TDATA_int_regslice[191:160]}};

assign mul_ln691_53_fu_1035_p1 = {{inStream1_TDATA_int_regslice[447:416]}};

assign mul_ln691_54_fu_1041_p0 = {{inStream2_TDATA_int_regslice[319:288]}};

assign mul_ln691_54_fu_1041_p1 = {{inStream1_TDATA_int_regslice[479:448]}};

assign mul_ln691_55_fu_1047_p0 = {{inStream2_TDATA_int_regslice[447:416]}};

assign mul_ln691_55_fu_1047_p1 = {{inStream1_TDATA_int_regslice[511:480]}};

assign mul_ln691_56_fu_1071_p0 = {{inStream2_TDATA_int_regslice[95:64]}};

assign mul_ln691_56_fu_1071_p1 = {{inStream1_TDATA_int_regslice[415:384]}};

assign mul_ln691_57_fu_1077_p0 = {{inStream2_TDATA_int_regslice[223:192]}};

assign mul_ln691_57_fu_1077_p1 = {{inStream1_TDATA_int_regslice[447:416]}};

assign mul_ln691_58_fu_1083_p0 = {{inStream2_TDATA_int_regslice[351:320]}};

assign mul_ln691_58_fu_1083_p1 = {{inStream1_TDATA_int_regslice[479:448]}};

assign mul_ln691_59_fu_1089_p0 = {{inStream2_TDATA_int_regslice[479:448]}};

assign mul_ln691_59_fu_1089_p1 = {{inStream1_TDATA_int_regslice[511:480]}};

assign mul_ln691_5_fu_531_p0 = {{inStream2_TDATA_int_regslice[191:160]}};

assign mul_ln691_5_fu_531_p1 = {{inStream1_TDATA_int_regslice[63:32]}};

assign mul_ln691_60_fu_1113_p0 = {{inStream2_TDATA_int_regslice[127:96]}};

assign mul_ln691_60_fu_1113_p1 = {{inStream1_TDATA_int_regslice[415:384]}};

assign mul_ln691_61_fu_1119_p0 = {{inStream2_TDATA_int_regslice[255:224]}};

assign mul_ln691_61_fu_1119_p1 = {{inStream1_TDATA_int_regslice[447:416]}};

assign mul_ln691_62_fu_1125_p0 = {{inStream2_TDATA_int_regslice[383:352]}};

assign mul_ln691_62_fu_1125_p1 = {{inStream1_TDATA_int_regslice[479:448]}};

assign mul_ln691_63_fu_1131_p0 = {{inStream2_TDATA_int_regslice[511:480]}};

assign mul_ln691_63_fu_1131_p1 = {{inStream1_TDATA_int_regslice[511:480]}};

assign mul_ln691_6_fu_537_p0 = {{inStream2_TDATA_int_regslice[319:288]}};

assign mul_ln691_6_fu_537_p1 = {{inStream1_TDATA_int_regslice[95:64]}};

assign mul_ln691_7_fu_543_p0 = {{inStream2_TDATA_int_regslice[447:416]}};

assign mul_ln691_7_fu_543_p1 = {{inStream1_TDATA_int_regslice[127:96]}};

assign mul_ln691_8_fu_567_p0 = {{inStream2_TDATA_int_regslice[95:64]}};

assign mul_ln691_9_fu_573_p0 = {{inStream2_TDATA_int_regslice[223:192]}};

assign mul_ln691_9_fu_573_p1 = {{inStream1_TDATA_int_regslice[63:32]}};

assign outStream_TDATA_int_regslice = {{{{{{{{{{{{{{{{add_ln691_47_fu_1149_p2}, {add_ln691_44_fu_1107_p2}}, {add_ln691_41_fu_1065_p2}}, {add_ln691_38_fu_1023_p2}}, {add_ln691_35_fu_981_p2}}, {add_ln691_32_fu_939_p2}}, {add_ln691_29_fu_897_p2}}, {add_ln691_26_fu_855_p2}}, {add_ln691_23_fu_813_p2}}, {add_ln691_20_fu_771_p2}}, {add_ln691_17_fu_729_p2}}, {add_ln691_14_fu_687_p2}}, {add_ln691_11_fu_645_p2}}, {add_ln691_8_fu_603_p2}}, {add_ln691_5_fu_561_p2}}, {add_ln691_2_fu_519_p2}};

assign outStream_TVALID = regslice_both_outStream_V_data_V_U_vld_out;

assign trunc_ln674_1_fu_179_p1 = inStream2_TDATA_int_regslice[31:0];

assign trunc_ln674_fu_175_p1 = inStream1_TDATA_int_regslice[31:0];

endmodule //test
